apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3-app
spec:
  replicas: 3
  selector: 
    matchLabels:     
      app: team3-app
  template:
    metadata:
      labels:
        app: team3-app
        env: demo
    spec:
      containers:
      - name: team3-app
        image: bkits/devops-team3:v4
        ports:
        - containerPort: 80
     
